// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijtgkcxvkeoimepqzfys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdGdrY3h2a2VvaW1lcHF6ZnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTM0NDMsImV4cCI6MjA2NjY2OTQ0M30.JEBHGdxRFX9kWkHWwGNmyiawMvEraQsgCwoqAqEuK2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);